---

- name: Prepare data directory
  file: path="{{ traffic_data_dir }}/flent" state=directory

- name: Default server targets
  set_fact:
    server_targets: "{{ groups['netdiag_servers'] }}"
  when: server_targets is not defined

- name: Upload test configuration (Python {{ ansible_python_version }})
  copy:
    src: "{{ test_conf_src }}"
    dest: "{{ netdiag_venv}}/lib/python{{ ansible_python_version.rsplit('.', 1)[0] }}/site-packages/flent/tests/{{ test_conf_name }}.conf"

- name: Upload test wrapper script
  template: src=flent.wrapper.sh.j2 dest="{{ netdiag_venv }}/bin/flent.{{ item }}.sh" mode=0755
  with_items:
    - "duplex"
    - "upload"
    - "download"
  
- name: Execute test wrapper script (duplex)
  shell: "{{ netdiag_venv }}/bin/flent.duplex.sh"

- name: Execute test wrapper script (upload)
  shell: "{{ netdiag_venv }}/bin/flent.upload.sh"

- name: Execute test wrapper script (download)
  shell: "{{ netdiag_venv }}/bin/flent.download.sh"

- name: Remove test wrapper script
  shell: "rm -f {{ netdiag_venv }}/bin/flent.*.sh"
