---
- name: List data files to fetch
  shell: "(cd {{ traffic_data_dir }}; find . -maxdepth 1 -type f) | cut -d'/' -f2"
  register: files_to_copy

- name: Fetch data files
  fetch: src="{{ traffic_data_dir }}/{{ item }}" dest="{{ local_traffic_data_dir }}/" flat=True
  with_items: "{{ files_to_copy.stdout_lines }}"
